namespace HRConnect.Api.Services
{
  using System.Collections.Generic;
  using System.Globalization;
  using System.Threading.Tasks;
  using HRConnect.Api.DTOs.Payroll.Deduction;
  using HRConnect.Api.Interfaces;
  using HRConnect.Api.Interfaces.Payroll.Deduction;
  using HRConnect.Api.Mappers.Payroll.Deduction;
  using HRConnect.Api.Models;
  using HRConnect.Api.Models.Payroll;
  using HRConnect.Api.Models.PayrollDeduction;
  using HRConnect.Api.Utils;
  using HRConnect.Api.Utils.ValidationHelpers.Deduction;

  public class DeductionService(IDeductionRepository deductionRepository, IEmployeeDeductionRepository employeeDeductionRepository,
    IEmployeeRepository employeeRepository, IPayrollRunRepository payrollRunRepository) : IDeductionService
  {
    private readonly IDeductionRepository _deductionRepository = deductionRepository;
    private readonly IEmployeeDeductionRepository _employeeDeductionRepository = employeeDeductionRepository;
    private readonly IEmployeeRepository _employeeRepository = employeeRepository;
    private readonly IPayrollRunRepository _payrollRunRepository = payrollRunRepository;
    private readonly decimal UIFSalaryCap = 17712m;
    private readonly decimal UIFDeductionCap = 177.12m;

    ///<summary>
    ///Adds a new deduction to the system.
    ///</summary>
    ///<param name="deductionAddDto">Deduction add request data transfer object</param>
    ///<returns>
    ///Added deduction data transfer object
    ///</returns>
    ///<exception cref="ValidationException"></exception>
    public async Task<DeductionDto> AddAsync(DeductionAddDto deductionAddDto)
    {
      ValidateDeductionDto.ValidateDeductionAddDto(deductionAddDto);
      await CheckForSimilarDescriptions(deductionAddDto.ShortDescription, deductionAddDto.LongDescription);
      Deduction deduction = deductionAddDto.ToDeductionModel();
      if (deduction.DeductionId is not null and not "")
      {
        throw new ValidationException("Deduction code is auto-generated by the system");
      }
      else
      {
        string companyIdPrefix = deductionAddDto.CompanyId[..3].ToUpper(CultureInfo.InvariantCulture);
        List<string> existingDeductionCodes = await _deductionRepository.GetAllDeductionCodesAsync(companyIdPrefix);
        deduction.DeductionId = GenerateUnqiueCode.GenerateStringCode(companyIdPrefix, existingDeductionCodes);
        deduction.Status = true;
        deduction.ModifiedDate = DateTime.Now;
        Deduction addedDeduction = await _deductionRepository.AddAsync(deduction);
        return addedDeduction.ToDeductionDto();
      }
    }

    ///<summary>
    ///Set the status of a deduction to inactive instead of deleting it from the database. 
    ///</summary>
    ///<param name="code">Code of deduction to be set inactive</param>
    ///<returns>
    ///String message indicating the deduction has been set to inactive.
    ///</returns>
    public async Task<string> DeleteAsync(string code)
    {
      return await _deductionRepository.DeleteAsync(code);
    }

    ///<summary>
    ///Retrieves all deductions from the system.
    ///</summary>
    ///<returns>
    ///List of deduction data transfer objects
    ///</returns>
    public async Task<List<DeductionDto>> GetAllDeductionsAsync()
    {
      List<Deduction> deductions = await _deductionRepository.GetAllDeductionsAsync();

      return deductions.Select(d => d.ToDeductionDto()).ToList();
    }

    ///<summary>
    ///Retrieves all deductions for a specific company from the system.
    ///</summary>
    ///<param name="companyId">Company ID</param>
    ///<returns>
    ///List of deductions for the specified company
    ///</returns>
    public async Task<List<DeductionDto>> GetDeductionsByCompanyIdAsync(string companyId)
    {
      List<Deduction> deductions = await _deductionRepository.GetDeductionByCompanyIdAsync(companyId);
      return deductions.Select(d => d.ToDeductionDto()).ToList();
    }

    ///<summary>
    ///Retrieves a deduction by its code.
    ///</summary>
    ///<param name="code">Code of the deduction to retrieve</param>
    ///<returns>
    ///Deduction with the specified code
    ///</returns>
    ///<exception cref="NotFoundException"></exception>
    public async Task<DeductionDto?> GetDeductionByCodeAsync(string code)
    {
      Deduction? deduction = await _deductionRepository.GetDeductionByCodeAsync(code)
        ?? throw new NotFoundException($"Deduction with code {code} not found");

      return deduction.ToDeductionDto();
    }

    ///<summary>
    ///Updates an existing deduction in the system.
    ///</summary>
    ///<param name="deductionUpdateDto">Deduction update request data transfer object</param>
    ///<returns>
    ///Updated deduction details
    ///</returns>
    ///<exception cref="NotFoundException"></exception>
    public async Task<DeductionDto> UpdateAsync(DeductionUpdateDto deductionUpdateDto)
    {
      ValidateDeductionDto.ValidateDeductionUpdateDto(deductionUpdateDto);
      await CheckForSimilarDescriptions(deductionUpdateDto.ShortDescription, deductionUpdateDto.LongDescription);
      Deduction? deduction = await _deductionRepository.GetDeductionByCodeAsync(deductionUpdateDto.DeductionId)
        ?? throw new NotFoundException($"Deduction with code {deductionUpdateDto.DeductionId} not found");
      deduction.CompanyId = deductionUpdateDto.CompanyId ?? deduction.CompanyId;
      deduction.TaxCode = deductionUpdateDto.TaxCode ?? deduction.TaxCode;
      deduction.ShortDescription = deductionUpdateDto.ShortDescription ?? deduction.ShortDescription;
      deduction.LongDescription = deductionUpdateDto.LongDescription ?? deduction.LongDescription;
      deduction.DeductionType = deductionUpdateDto.DeductionType ?? deduction.DeductionType;
      deduction.InputType = deductionUpdateDto.InputType ?? deduction.InputType;
      deduction.MinimumValue = deductionUpdateDto.MinimumValue ?? deduction.MinimumValue;
      deduction.MaximumValue = deductionUpdateDto.MaximumValue ?? deduction.MaximumValue;
      deduction.EmployerContributed = deductionUpdateDto.EmployerContributed ?? deduction.EmployerContributed;
      deduction.Status = deductionUpdateDto.Status ?? deduction.Status;
      deduction.ModifiedDate = DateTime.Now;

      Deduction updatedDeduction = await _deductionRepository.UpdateAsync(deduction);

      await HandleDeductionUpdate(updatedDeduction);

      return updatedDeduction.ToDeductionDto();
    }

    /// <summary>
    ///Auxilary method to check if the short description or long description of a payroll earning already exists in the database. I
    ///</summary>
    ///<param name="shortDescription">The short description of the payroll earning</param>
    ///<param name="longDescription">The long description of the payroll earning</param>
    ///<exception cref="ValidationException"></exception>
    private async Task CheckForSimilarDescriptions(string? shortDescription, string? longDescription)
    {
      bool descriptionExists = await _deductionRepository.CheckIfDescriptionsExists(shortDescription ?? "", longDescription ?? "");
      if (descriptionExists)
      {
        throw new ValidationException("A deduction with the same short description and long description already exists");
      }
    }

    ///<summary>
    ///Auxilary method to update deductions for employees in the current pyaroll run 
    ///</summary>
    ///<param name="payrollEarning">Payroll run model</param>
    ///<exception cref="NotFoundException"></exception>
    public async Task HandleDeductionUpdate(Deduction deduction)
    {
      PayrollRun? currentPayrollRun = await _payrollRunRepository.GetCurrentRunAsync() ?? throw new NotFoundException("Current payroll run not found");
      List<EmployeeDeduction> employeeDeductions = await _employeeDeductionRepository.GetByPayrollRunIdAsync(currentPayrollRun.PayrollRunId);

      foreach (EmployeeDeduction employeeDeduction in employeeDeductions)
      {
        Employee? employee = await _employeeRepository.GetEmployeeByIdAsync(employeeDeduction.EmployeeId);
        if (employee != null)
        {
          employeeDeduction.DeductionType = deduction.DeductionType;
          employeeDeduction.DeductionInputType = deduction.InputType;

          if (employeeDeduction.DeductionInputType == DeductionInputType.Amount)
          {
            employeeDeduction.AmountOrPercentage = ValidateDeductionAmount(deduction.MaximumValue, deduction.MinimumValue, employeeDeduction.AmountOrPercentage);
            employeeDeduction.CalculatedDeductionAmount = ValidateDeductionAmount(deduction.MaximumValue, deduction.MinimumValue, employeeDeduction.AmountOrPercentage);
          }
          else if (employeeDeduction.DeductionInputType == DeductionInputType.Percentage)
          {
            employeeDeduction.CalculatedDeductionAmount = (deduction.DeductionType == "UIF")
              ? CalculateUIF(employee.MonthlySalary)
              : Math.Round(employee.MonthlySalary * (employeeDeduction.AmountOrPercentage / 100));
          }
        }
      }

      try
      {
        await _employeeDeductionRepository.UpdateRangeAsync(employeeDeductions);
      }
      catch (Exception ex)
      {
        Console.WriteLine(ex.ToString());
      }
    }

    ///<summary>
    ///Validate that employee deduction amount is not more than deduction maximum value and is not lower than deduction minimum value 
    ///</summary>
    ///<param name="MaximumValue">Deduction maximum value</param>
    ///<param name="MinimumValue">Deduction minimum value</param>
    ///<param name="Amount">Employee deduction amount</param>
    ///<exception cref="ValidationException"></exception>
    private decimal ValidateDeductionAmount(decimal? MaximumValue, decimal? MinimumValue, decimal Amount)
    {
      if (MaximumValue != null && Amount > MaximumValue)
      {
        return (decimal)MaximumValue;
      }

      if (MinimumValue != null && Amount < MinimumValue)
      {
        return (decimal)MinimumValue;
      }

      return Amount;
    }

    ///<summary>
    ///Auxilary function to determine employee UIF deduction 
    ///</summary>
    ///<param name="monthlySalary">Employee monthly salary</param>
    ///<returns>
    ///UIF deduction given employee's salary
    ///</returns>
    private decimal CalculateUIF(decimal monthlySalary)
    {
      return monthlySalary > UIFSalaryCap ? UIFDeductionCap : monthlySalary * 0.01m;
    }
  }
}
