// <auto-generated />
using System;
using HRConnect.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRConnect.Api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260216085436_UpdatingDBWithNonNulls")]
    partial class UpdatingDBWithNonNulls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRConnect.Api.Models.MedicalOption", b =>
                {
                    b.Property<int>("MedicalOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedicalOptionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalOptionId"));

                    b.Property<int>("MedicalOptionCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("MedicalOptionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MonthlyMsaContributionAdult")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal?>("MonthlyMsaContributionChild")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal?>("MonthlyMsaContributionPrincipal")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal>("MonthlyRiskContributionAdult")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal>("MonthlyRiskContributionChild")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal?>("MonthlyRiskContributionChild2")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal?>("MonthlyRiskContributionPrincipal")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal>("SalaryBracketMax")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal>("SalaryBracketMin")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal>("TotalMonthlyContributionsAdult")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal>("TotalMonthlyContributionsChild")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal?>("TotalMonthlyContributionsChild2")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal?>("TotalMonthlyContributionsPrincipal")
                        .HasColumnType("decimal(15, 2)");

                    b.HasKey("MedicalOptionId");

                    b.HasIndex("MedicalOptionCategoryId");

                    b.ToTable("MedicalOptions");
                });

            modelBuilder.Entity("HRConnect.Api.Models.MedicalOptionCategory", b =>
                {
                    b.Property<int>("MedicalOptionCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedicalOptionCategoryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalOptionCategoryId"));

                    b.Property<string>("MedicalOptionCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedicalOptionCategoryId");

                    b.ToTable("MedicalOptionCategories");
                });

            modelBuilder.Entity("HRConnect.Api.Models.PasswordHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PasswordHistories");
                });

            modelBuilder.Entity("HRConnect.Api.Models.PasswordResetPin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PasswordResetPins");
                });

            modelBuilder.Entity("HRConnect.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HRConnect.Api.Models.MedicalOption", b =>
                {
                    b.HasOne("HRConnect.Api.Models.MedicalOptionCategory", "MedicalOptionCategory")
                        .WithMany("MedicalOptions")
                        .HasForeignKey("MedicalOptionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalOptionCategory");
                });

            modelBuilder.Entity("HRConnect.Api.Models.MedicalOptionCategory", b =>
                {
                    b.Navigation("MedicalOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
