// <auto-generated />
using System;
using HRConnect.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRConnect.Api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260218091156_AddLastResetYearToImployeeLeaveBalance")]
    partial class AddLastResetYearToImployeeLeaveBalance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRConnect.Api.Models.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("ReportingManagerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeId");

                    b.HasIndex("PositionId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HRConnect.Api.Models.EmployeeLeaveBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccruedDays")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("EntitledDays")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("LastResetYear")
                        .HasColumnType("int");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("RemainingDays")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UsedDays")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("EmployeeLeaveBalances");
                });

            modelBuilder.Entity("HRConnect.Api.Models.JobGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("JobGrades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Unskilled–Middle"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Senior Management"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Executive Director"
                        });
                });

            modelBuilder.Entity("HRConnect.Api.Models.LeaveApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DaysRequested")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveApplications");
                });

            modelBuilder.Entity("HRConnect.Api.Models.LeaveEntitlementRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DaysAllocated")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("JobGradeId")
                        .HasColumnType("int");

                    b.Property<int?>("JobGradeId1")
                        .HasColumnType("int");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxYearsService")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinYearsService")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("JobGradeId");

                    b.HasIndex("JobGradeId1");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveEntitlementRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DaysAllocated = 15,
                            IsActive = true,
                            JobGradeId = 1,
                            LeaveTypeId = 1,
                            MaxYearsService = 2.99m,
                            MinYearsService = 0m
                        },
                        new
                        {
                            Id = 2,
                            DaysAllocated = 18,
                            IsActive = true,
                            JobGradeId = 2,
                            LeaveTypeId = 1,
                            MaxYearsService = 2.99m,
                            MinYearsService = 0m
                        },
                        new
                        {
                            Id = 3,
                            DaysAllocated = 22,
                            IsActive = true,
                            JobGradeId = 3,
                            LeaveTypeId = 1,
                            MaxYearsService = 2.99m,
                            MinYearsService = 0m
                        },
                        new
                        {
                            Id = 4,
                            DaysAllocated = 18,
                            IsActive = true,
                            JobGradeId = 1,
                            LeaveTypeId = 1,
                            MaxYearsService = 5m,
                            MinYearsService = 3m
                        },
                        new
                        {
                            Id = 5,
                            DaysAllocated = 21,
                            IsActive = true,
                            JobGradeId = 2,
                            LeaveTypeId = 1,
                            MaxYearsService = 5m,
                            MinYearsService = 3m
                        },
                        new
                        {
                            Id = 6,
                            DaysAllocated = 25,
                            IsActive = true,
                            JobGradeId = 3,
                            LeaveTypeId = 1,
                            MaxYearsService = 5m,
                            MinYearsService = 3m
                        },
                        new
                        {
                            Id = 7,
                            DaysAllocated = 20,
                            IsActive = true,
                            JobGradeId = 1,
                            LeaveTypeId = 1,
                            MinYearsService = 5.01m
                        },
                        new
                        {
                            Id = 8,
                            DaysAllocated = 23,
                            IsActive = true,
                            JobGradeId = 2,
                            LeaveTypeId = 1,
                            MinYearsService = 5.01m
                        },
                        new
                        {
                            Id = 9,
                            DaysAllocated = 27,
                            IsActive = true,
                            JobGradeId = 3,
                            LeaveTypeId = 1,
                            MinYearsService = 5.01m
                        },
                        new
                        {
                            Id = 10,
                            DaysAllocated = 30,
                            IsActive = true,
                            JobGradeId = 1,
                            LeaveTypeId = 2,
                            MinYearsService = 0m
                        },
                        new
                        {
                            Id = 11,
                            DaysAllocated = 30,
                            IsActive = true,
                            JobGradeId = 2,
                            LeaveTypeId = 2,
                            MinYearsService = 0m
                        },
                        new
                        {
                            Id = 12,
                            DaysAllocated = 30,
                            IsActive = true,
                            JobGradeId = 3,
                            LeaveTypeId = 2,
                            MinYearsService = 0m
                        },
                        new
                        {
                            Id = 13,
                            DaysAllocated = 120,
                            IsActive = true,
                            JobGradeId = 1,
                            LeaveTypeId = 3,
                            MinYearsService = 0m
                        },
                        new
                        {
                            Id = 14,
                            DaysAllocated = 3,
                            IsActive = true,
                            JobGradeId = 1,
                            LeaveTypeId = 4,
                            MinYearsService = 0m
                        },
                        new
                        {
                            Id = 15,
                            DaysAllocated = 3,
                            IsActive = true,
                            JobGradeId = 2,
                            LeaveTypeId = 4,
                            MinYearsService = 0m
                        },
                        new
                        {
                            Id = 16,
                            DaysAllocated = 3,
                            IsActive = true,
                            JobGradeId = 3,
                            LeaveTypeId = 4,
                            MinYearsService = 0m
                        });
                });

            modelBuilder.Entity("HRConnect.Api.Models.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarryoverExpiryDay")
                        .HasColumnType("int");

                    b.Property<int?>("CarryoverExpiryMonth")
                        .HasColumnType("int");

                    b.Property<int?>("CarryoverNotificationDay")
                        .HasColumnType("int");

                    b.Property<int?>("CarryoverNotificationMonth")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FemaleOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRollingWindow")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxCarryoverDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResetDay")
                        .HasColumnType("int");

                    b.Property<int?>("ResetMonth")
                        .HasColumnType("int");

                    b.Property<int?>("RollingMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarryoverExpiryDay = 1,
                            CarryoverExpiryMonth = 1,
                            CarryoverNotificationDay = 1,
                            CarryoverNotificationMonth = 12,
                            Code = "AL",
                            Description = "Annual Leave Policy",
                            FemaleOnly = false,
                            IsActive = true,
                            IsRollingWindow = false,
                            MaxCarryoverDays = 5,
                            Name = "Annual Leave",
                            ResetDay = 1,
                            ResetMonth = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "SL",
                            Description = "Sick Leave Policy",
                            FemaleOnly = false,
                            IsActive = true,
                            IsRollingWindow = true,
                            Name = "Sick Leave",
                            RollingMonths = 36
                        },
                        new
                        {
                            Id = 3,
                            Code = "ML",
                            Description = "Maternity Leave Policy",
                            FemaleOnly = true,
                            IsActive = true,
                            IsRollingWindow = false,
                            Name = "Maternity Leave"
                        },
                        new
                        {
                            Id = 4,
                            Code = "FRL",
                            Description = "Family Responsibility Policy",
                            FemaleOnly = false,
                            IsActive = true,
                            IsRollingWindow = true,
                            Name = "Family Responsibility Leave",
                            RollingMonths = 12
                        });
                });

            modelBuilder.Entity("HRConnect.Api.Models.PasswordHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PasswordHistories");
                });

            modelBuilder.Entity("HRConnect.Api.Models.PasswordResetPin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PasswordResetPins");
                });

            modelBuilder.Entity("HRConnect.Api.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<int>("JobGradeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PositionId");

                    b.HasIndex("JobGradeId");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            PositionId = 1,
                            JobGradeId = 1,
                            Title = "Unskilled"
                        },
                        new
                        {
                            PositionId = 2,
                            JobGradeId = 1,
                            Title = "Skilled/Semi Skilled"
                        },
                        new
                        {
                            PositionId = 3,
                            JobGradeId = 1,
                            Title = "Junior Management"
                        },
                        new
                        {
                            PositionId = 4,
                            JobGradeId = 1,
                            Title = "Middle Management"
                        },
                        new
                        {
                            PositionId = 5,
                            JobGradeId = 2,
                            Title = "Top/Senior Management"
                        },
                        new
                        {
                            PositionId = 6,
                            JobGradeId = 3,
                            Title = "Executive Director"
                        });
                });

            modelBuilder.Entity("HRConnect.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HRConnect.Api.Models.Employee", b =>
                {
                    b.HasOne("HRConnect.Api.Models.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("HRConnect.Api.Models.EmployeeLeaveBalance", b =>
                {
                    b.HasOne("HRConnect.Api.Models.Employee", "Employee")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRConnect.Api.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("HRConnect.Api.Models.LeaveApplication", b =>
                {
                    b.HasOne("HRConnect.Api.Models.Employee", "Employee")
                        .WithMany("LeaveApplications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRConnect.Api.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("HRConnect.Api.Models.LeaveEntitlementRule", b =>
                {
                    b.HasOne("HRConnect.Api.Models.JobGrade", "JobGrade")
                        .WithMany()
                        .HasForeignKey("JobGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRConnect.Api.Models.JobGrade", null)
                        .WithMany("LeaveEntitlementRules")
                        .HasForeignKey("JobGradeId1");

                    b.HasOne("HRConnect.Api.Models.LeaveType", "LeaveType")
                        .WithMany("EntitlementRules")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobGrade");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("HRConnect.Api.Models.Position", b =>
                {
                    b.HasOne("HRConnect.Api.Models.JobGrade", "JobGrade")
                        .WithMany()
                        .HasForeignKey("JobGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobGrade");
                });

            modelBuilder.Entity("HRConnect.Api.Models.Employee", b =>
                {
                    b.Navigation("LeaveApplications");

                    b.Navigation("LeaveBalances");
                });

            modelBuilder.Entity("HRConnect.Api.Models.JobGrade", b =>
                {
                    b.Navigation("LeaveEntitlementRules");
                });

            modelBuilder.Entity("HRConnect.Api.Models.LeaveType", b =>
                {
                    b.Navigation("EntitlementRules");
                });

            modelBuilder.Entity("HRConnect.Api.Models.Position", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
