// <auto-generated />
using System;
using HRConnect.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRConnect.Api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260206094523_MedicalOptionsAndCategoryModelUpdateV1")]
    partial class MedicalOptionsAndCategoryModelUpdateV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRConnect.Api.Models.MedicalOption", b =>
                {
                    b.Property<int>("MedicalOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedicalOptionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalOptionId"));

                    b.Property<decimal>("AdultAmount")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal>("Child1Amount")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal?>("Child2Amount")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<int>("MedicalOptionCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("MedicalOptionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PrincipalAmount")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal?>("SalaryBracketMax")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal?>("SalaryBracketMin")
                        .HasColumnType("decimal(15, 2)");

                    b.HasKey("MedicalOptionId");

                    b.HasIndex("MedicalOptionCategoryId")
                        .IsUnique();

                    b.ToTable("MedicalOptions");
                });

            modelBuilder.Entity("HRConnect.Api.Models.MedicalOptionCategory", b =>
                {
                    b.Property<int>("MedicalOptionCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedicalOptionCategoryId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalOptionCategoryId"));

                    b.Property<string>("MedicalOptionCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MonthlyMsaContributionAdult")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal?>("MonthlyMsaContributionChild")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal?>("MonthlyMsaContributionPrincipal")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal>("MonthlyRiskContributionAdult")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal>("MonthlyRiskContributionChild")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal?>("MonthlyRiskContributionChild2")
                        .HasColumnType("decimal(15, 2)");

                    b.Property<decimal>("MonthlyRiskContributionPrincipal")
                        .HasColumnType("decimal(15, 2)");

                    b.HasKey("MedicalOptionCategoryId");

                    b.ToTable("MedicalOptionCategories");
                });

            modelBuilder.Entity("HRConnect.Api.Models.PasswordHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PasswordHistories");
                });

            modelBuilder.Entity("HRConnect.Api.Models.PasswordResetPin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PasswordResetPins");
                });

            modelBuilder.Entity("HRConnect.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HRConnect.Api.Models.MedicalOption", b =>
                {
                    b.HasOne("HRConnect.Api.Models.MedicalOptionCategory", "Category")
                        .WithOne("MedicalOption")
                        .HasForeignKey("HRConnect.Api.Models.MedicalOption", "MedicalOptionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HRConnect.Api.Models.MedicalOptionCategory", b =>
                {
                    b.Navigation("MedicalOption")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
