// <auto-generated />
using System;
using HRConnect.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRConnect.Api.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRConnect.Api.Models.AnnualLeaveAccrualHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Accrued")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ClosingBalance")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Forfeited")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("OpeningBalance")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Used")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AnnualLeaveAccrualHistories");
                });

            modelBuilder.Entity("HRConnect.Api.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CareerManagerID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EmployeeId");

                    b.HasIndex("CareerManagerID");

                    b.HasIndex("PositionId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HRConnect.Api.Models.EmployeeAccrualRateHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualEntitlement")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("EmployeeId", "EffectiveFrom")
                        .IsUnique();

                    b.ToTable("EmployeeAccrualRateHistories");
                });

            modelBuilder.Entity("HRConnect.Api.Models.EmployeeLeaveBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccruedDays")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("AvailableDays")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CarryoverDays")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ForfeitedDays")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly?>("LastAccrualDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("LastCalculatedDate")
                        .HasColumnType("date");

                    b.Property<int?>("LastResetYear")
                        .HasColumnType("int");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("TakenDays")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("EmployeeId", "LeaveTypeId")
                        .IsUnique();

                    b.ToTable("EmployeeLeaveBalances");
                });

            modelBuilder.Entity("HRConnect.Api.Models.JobGrade", b =>
                {
                    b.Property<int>("JobGradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobGradeId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("JobGradeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("JobGrades");

                    b.HasData(
                        new
                        {
                            JobGradeId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Unskilled–Middle",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            JobGradeId = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Senior Management",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            JobGradeId = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Executive Director",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HRConnect.Api.Models.LeaveApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ApprovalToken")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DaysRequested")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("DecisionBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("TokenExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("EmployeeId", "StartDate", "EndDate");

                    b.ToTable("LeaveApplications");
                });

            modelBuilder.Entity("HRConnect.Api.Models.LeaveEntitlementRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DaysAllocated")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("JobGradeId")
                        .HasColumnType("int");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxYearsService")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MinYearsService")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("JobGradeId");

                    b.HasIndex("LeaveTypeId", "JobGradeId", "MinYearsService")
                        .IsUnique();

                    b.ToTable("LeaveEntitlementRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DaysAllocated = 15m,
                            IsActive = true,
                            JobGradeId = 1,
                            LeaveTypeId = 1,
                            MaxYearsService = 2.99m,
                            MinYearsService = 0m
                        },
                        new
                        {
                            Id = 2,
                            DaysAllocated = 18m,
                            IsActive = true,
                            JobGradeId = 2,
                            LeaveTypeId = 1,
                            MaxYearsService = 2.99m,
                            MinYearsService = 0m
                        },
                        new
                        {
                            Id = 3,
                            DaysAllocated = 22m,
                            IsActive = true,
                            JobGradeId = 3,
                            LeaveTypeId = 1,
                            MaxYearsService = 2.99m,
                            MinYearsService = 0m
                        },
                        new
                        {
                            Id = 4,
                            DaysAllocated = 18m,
                            IsActive = true,
                            JobGradeId = 1,
                            LeaveTypeId = 1,
                            MaxYearsService = 5m,
                            MinYearsService = 3m
                        },
                        new
                        {
                            Id = 5,
                            DaysAllocated = 21m,
                            IsActive = true,
                            JobGradeId = 2,
                            LeaveTypeId = 1,
                            MaxYearsService = 5m,
                            MinYearsService = 3m
                        },
                        new
                        {
                            Id = 6,
                            DaysAllocated = 25m,
                            IsActive = true,
                            JobGradeId = 3,
                            LeaveTypeId = 1,
                            MaxYearsService = 5m,
                            MinYearsService = 3m
                        },
                        new
                        {
                            Id = 7,
                            DaysAllocated = 20m,
                            IsActive = true,
                            JobGradeId = 1,
                            LeaveTypeId = 1,
                            MinYearsService = 5.01m
                        },
                        new
                        {
                            Id = 8,
                            DaysAllocated = 23m,
                            IsActive = true,
                            JobGradeId = 2,
                            LeaveTypeId = 1,
                            MinYearsService = 5.01m
                        },
                        new
                        {
                            Id = 9,
                            DaysAllocated = 27m,
                            IsActive = true,
                            JobGradeId = 3,
                            LeaveTypeId = 1,
                            MinYearsService = 5.01m
                        },
                        new
                        {
                            Id = 10,
                            DaysAllocated = 30m,
                            IsActive = true,
                            JobGradeId = 1,
                            LeaveTypeId = 2,
                            MinYearsService = 0m
                        },
                        new
                        {
                            Id = 11,
                            DaysAllocated = 30m,
                            IsActive = true,
                            JobGradeId = 2,
                            LeaveTypeId = 2,
                            MinYearsService = 0m
                        },
                        new
                        {
                            Id = 12,
                            DaysAllocated = 30m,
                            IsActive = true,
                            JobGradeId = 3,
                            LeaveTypeId = 2,
                            MinYearsService = 0m
                        },
                        new
                        {
                            Id = 13,
                            DaysAllocated = 120m,
                            IsActive = true,
                            JobGradeId = 1,
                            LeaveTypeId = 3,
                            MinYearsService = 0m
                        },
                        new
                        {
                            Id = 14,
                            DaysAllocated = 3m,
                            IsActive = true,
                            JobGradeId = 1,
                            LeaveTypeId = 4,
                            MinYearsService = 0m
                        },
                        new
                        {
                            Id = 15,
                            DaysAllocated = 3m,
                            IsActive = true,
                            JobGradeId = 2,
                            LeaveTypeId = 4,
                            MinYearsService = 0m
                        },
                        new
                        {
                            Id = 16,
                            DaysAllocated = 3m,
                            IsActive = true,
                            JobGradeId = 3,
                            LeaveTypeId = 4,
                            MinYearsService = 0m
                        });
                });

            modelBuilder.Entity("HRConnect.Api.Models.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CarryoverExpiryDay")
                        .HasColumnType("int");

                    b.Property<int?>("CarryoverExpiryMonth")
                        .HasColumnType("int");

                    b.Property<int?>("CarryoverNotificationDay")
                        .HasColumnType("int");

                    b.Property<int?>("CarryoverNotificationMonth")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FemaleOnly")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRollingWindow")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxCarryoverDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ResetDay")
                        .HasColumnType("int");

                    b.Property<int?>("ResetMonth")
                        .HasColumnType("int");

                    b.Property<int?>("RollingMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarryoverExpiryDay = 1,
                            CarryoverExpiryMonth = 1,
                            CarryoverNotificationDay = 1,
                            CarryoverNotificationMonth = 12,
                            Code = "AL",
                            Description = "Annual Leave Policy",
                            FemaleOnly = false,
                            IsActive = true,
                            IsRollingWindow = false,
                            MaxCarryoverDays = 5,
                            Name = "Annual Leave",
                            ResetDay = 1,
                            ResetMonth = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "SL",
                            Description = "Sick Leave Policy",
                            FemaleOnly = false,
                            IsActive = true,
                            IsRollingWindow = true,
                            Name = "Sick Leave",
                            RollingMonths = 36
                        },
                        new
                        {
                            Id = 3,
                            Code = "ML",
                            Description = "Maternity Leave Policy",
                            FemaleOnly = true,
                            IsActive = true,
                            IsRollingWindow = false,
                            Name = "Maternity Leave"
                        },
                        new
                        {
                            Id = 4,
                            Code = "FRL",
                            Description = "Family Responsibility Policy",
                            FemaleOnly = false,
                            IsActive = true,
                            IsRollingWindow = true,
                            Name = "Family Responsibility Leave",
                            RollingMonths = 12
                        });
                });

            modelBuilder.Entity("HRConnect.Api.Models.OccupationalLevel", b =>
                {
                    b.Property<int>("OccupationalLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OccupationalLevelId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OccupationalLevelId");

                    b.ToTable("OccupationalLevel");
                });

            modelBuilder.Entity("HRConnect.Api.Models.PasswordHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PasswordHistories");
                });

            modelBuilder.Entity("HRConnect.Api.Models.PasswordResetPin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PasswordResetPins");
                });

            modelBuilder.Entity("HRConnect.Api.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("JobGradeId")
                        .HasColumnType("int");

                    b.Property<int>("OccupationalLevelId")
                        .HasColumnType("int");

                    b.Property<string>("PositionTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PositionId");

                    b.HasIndex("JobGradeId");

                    b.HasIndex("OccupationalLevelId");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            PositionId = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            JobGradeId = 1,
                            OccupationalLevelId = 0,
                            PositionTitle = "Unskilled",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PositionId = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            JobGradeId = 1,
                            OccupationalLevelId = 0,
                            PositionTitle = "Skilled/Semi Skilled",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PositionId = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            JobGradeId = 1,
                            OccupationalLevelId = 0,
                            PositionTitle = "Junior Management",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PositionId = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            JobGradeId = 1,
                            OccupationalLevelId = 0,
                            PositionTitle = "Middle Management",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PositionId = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            JobGradeId = 2,
                            OccupationalLevelId = 0,
                            PositionTitle = "Top/Senior Management",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PositionId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            JobGradeId = 3,
                            OccupationalLevelId = 0,
                            PositionTitle = "Executive Director",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HRConnect.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HRConnect.Api.Models.AnnualLeaveAccrualHistory", b =>
                {
                    b.HasOne("HRConnect.Api.Models.Employee", "Employee")
                        .WithMany("AnnualLeaveAccrualHistories")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRConnect.Api.Models.Employee", b =>
                {
                    b.HasOne("HRConnect.Api.Models.Employee", "CareerManager")
                        .WithMany("Subordinates")
                        .HasForeignKey("CareerManagerID");

                    b.HasOne("HRConnect.Api.Models.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CareerManager");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("HRConnect.Api.Models.EmployeeAccrualRateHistory", b =>
                {
                    b.HasOne("HRConnect.Api.Models.Employee", "Employee")
                        .WithMany("AccrualRateHistory")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRConnect.Api.Models.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("HRConnect.Api.Models.EmployeeLeaveBalance", b =>
                {
                    b.HasOne("HRConnect.Api.Models.Employee", "Employee")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRConnect.Api.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("HRConnect.Api.Models.LeaveApplication", b =>
                {
                    b.HasOne("HRConnect.Api.Models.Employee", "Employee")
                        .WithMany("LeaveApplications")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRConnect.Api.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("HRConnect.Api.Models.LeaveEntitlementRule", b =>
                {
                    b.HasOne("HRConnect.Api.Models.JobGrade", "JobGrade")
                        .WithMany("LeaveEntitlementRules")
                        .HasForeignKey("JobGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRConnect.Api.Models.LeaveType", "LeaveType")
                        .WithMany("EntitlementRules")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobGrade");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("HRConnect.Api.Models.Position", b =>
                {
                    b.HasOne("HRConnect.Api.Models.JobGrade", "JobGrade")
                        .WithMany("Positions")
                        .HasForeignKey("JobGradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HRConnect.Api.Models.OccupationalLevel", "OccupationalLevels")
                        .WithMany("Positions")
                        .HasForeignKey("OccupationalLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobGrade");

                    b.Navigation("OccupationalLevels");
                });

            modelBuilder.Entity("HRConnect.Api.Models.Employee", b =>
                {
                    b.Navigation("AccrualRateHistory");

                    b.Navigation("AnnualLeaveAccrualHistories");

                    b.Navigation("LeaveApplications");

                    b.Navigation("LeaveBalances");

                    b.Navigation("Subordinates");
                });

            modelBuilder.Entity("HRConnect.Api.Models.JobGrade", b =>
                {
                    b.Navigation("LeaveEntitlementRules");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("HRConnect.Api.Models.LeaveType", b =>
                {
                    b.Navigation("EntitlementRules");
                });

            modelBuilder.Entity("HRConnect.Api.Models.OccupationalLevel", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("HRConnect.Api.Models.Position", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
